In [1]:
import numpy as np

## Basics


In [2]:
gene1 = [100, 200, 50, 400]
gene2 = [50, 0, 0, "error"]
gene3 = [350, 100, 50, True]
expression_data = [gene1, gene2, gene3]

In [3]:
expression_data

[[100, 200, 50, 400], [50, 0, 0, 'error'], [350, 100, 50, True]]

In [4]:
a = np.array(expression_data)
a

array([['100', '200', '50', '400'],
       ['50', '0', '0', 'error'],
       ['350', '100', '50', 'True']], dtype='<U11')

In [5]:
a.dtype

dtype('<U11')

In [6]:
arra_1=np.array([12,4,2,34])
print(arra_1)

[12  4  2 34]


In [7]:
arra_2=np.array([[12.4,12.3,1.33],[1,9.6,3.4]])
print(arra_2)

[[12.4  12.3   1.33]
 [ 1.    9.6   3.4 ]]


In [9]:
arra_2.ndim

2

In [10]:
arra_2.shape

(2, 3)

In [13]:
arra_1.dtype

dtype('int32')

## Getting Specific elements,rows and columns

In [14]:
arra_3=np.array([[12,45,22,56,2,45,8],[19,34,11,44,23,1,0]])
print(arra_3)

[[12 45 22 56  2 45  8]
 [19 34 11 44 23  1  0]]


In [15]:
arra_3[1,0]

19

In [16]:
arra_3[0,:]

array([12, 45, 22, 56,  2, 45,  8])

In [18]:
arra_3[0,:-1]
arra_3

array([[12, 45, 22, 56,  2, 45,  8],
       [19, 34, 11, 44, 23,  1,  0]])

In [19]:
arra_3[1,:3]

array([19, 34, 11])

In [20]:
arra_3[:,2]

array([22, 11])

In [21]:
arra_3[:,-1]

array([8, 0])

In [24]:
np.linspace(0,1,100)

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [25]:
np.random.randint(10,100,4)

array([58, 83, 15, 28])

In [26]:
A = np.array([1,0])
B = np.array([0,1])
D = A - B
D

array([ 1, -1])

In [27]:
A = np.array([2,3])
E = 2*A
E

array([4, 6])

In [29]:
np.ones(10,float)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [30]:
A = np.array([2,6,8,7,3])
H = A + 4
H

array([ 6, 10, 12, 11,  7])

In [31]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2  
print(result)

[[11 22 33]
 [14 25 36]]


In [32]:
A = np.array([2,6,8,7,3])
meanA = A.mean()
maxA = A.max()

print(meanA)
print(maxA)

5.2
8


In [ ]:
np.arange(10,20)

## Different Types OF Arrays

In [33]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [34]:
# np.full(shape, fill_value, dtype=None)
# for other values
np.full((4,2),23,dtype="float32")

array([[23., 23.],
       [23., 23.],
       [23., 23.],
       [23., 23.]], dtype=float32)

In [35]:
np.random.rand(2,3)

array([[0.2491184 , 0.70224533, 0.31595781],
       [0.36103063, 0.6131805 , 0.21663609]])

In [36]:
np.random.randint(3,size=(3,3))

array([[2, 0, 1],
       [2, 2, 0],
       [1, 2, 0]])

In [37]:
np.identity(2,dtype='int32')

array([[1, 0],
       [0, 1]])

In [ ]:
output=np.ones((5,5))
print(output)
z=np.zeros((3,3))
print(z)
z[1,1]=9
print(z)

In [ ]:

arra_5=np.array([12,3,6])
arra_6=arra_5
arra_6[0]=2
print(arra_5)



In [ ]:
arra_5=np.array([12,3,6])
arra_6=arra_5.copy()
arra_6[0]=2
print(arra_5)

## Mathematics

In [38]:
arra_7=np.array([1,2,3,4])
print(arra_7)

[1 2 3 4]


In [39]:
print(arra_7*8)
print(arra_7+3)
print(arra_7-2)
print(arra_7/2)

[ 8 16 24 32]
[4 5 6 7]
[-1  0  1  2]
[0.5 1.  1.5 2. ]


In [40]:
arra_8=np.array([[0,1,2,3],[4,5,6,7]])
arra_7+arra_8

array([[ 1,  3,  5,  7],
       [ 5,  7,  9, 11]])

In [41]:
print(arra_8)
trans=np.transpose(arra_8)
print(trans)

[[0 1 2 3]
 [4 5 6 7]]
[[0 4]
 [1 5]
 [2 6]
 [3 7]]


In [55]:
np.tan(90)

-1.995200412208242

In [48]:
np.cos()

-0.9524129804151563

## Linear Algebra

In [56]:
arra_9=np.ones((2,3))
print(arra_9)

arra_10=np.full((3,2),2)
print(arra_10)
np.matmul(arra_9,arra_10)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
arra_12=np.array([[12,45,22,56,2,45,8],[19,34,11,44,23,1,0]])
np.min(arra_12),np.max(arra_12),np.sum(arra_12)

In [ ]:
product=arra_11*arra_11
print(product)

In [ ]:
arra_1 = np.array([[0, 1], [1, 0]])
arra_2 = np.array([[1, 2], [0, 2]])
dot_prod = np.dot(arra_1,arra_2)
dot_prod

# Reorgnizing the Array

In [ ]:
before=np.array([[12,45,22,56,2,45,8],[19,34,11,44,23,1,0]])
print(before)
after=before.reshape((7,2))
print(after)

In [ ]:
arra_=np.arange(0,25).reshape(5,5)

In [ ]:
arra_

In [ ]:
arra_.sum(axis=0) 

In [ ]:
arra_.sum(axis=1) 

In [ ]:
matrix = np.eye(3)
print(matrix)